### ISSUE TITLE
RTL bullets appear on the LEFT instead of on the RIGHT.

### ISSUE THREAD

**Issue by alonidel** [dragonwocky/notion-enhancer#61] opened 2020-08-28 14:58 UTC
**describe the bug**
RTL support not full.
For example, bullets on RTL should appear on the LEFT instead of on the right.

**expected behaviour**
When RTL bullet should appear on the RIGHT of the text.

**screenshots**
![Screen Shot 2020-08-28 at 17 30 24](https://user-images.githubusercontent.com/47115834/91581820-a5203780-e957-11ea-9748-57fdf3e445fc.png)

**platform**
macOS

**Comment by dragonwocky** [comment] 2020-08-28 14:58
duplicate of #55

**Closed** 2020-08-28 14:59 UTC
Labels: bug
