### ISSUE TITLE
Config reset

### ISSUE THREAD

**Issue by Guilherme5342** [dragonwocky/notion-enhancer#71] opened 2020-08-31 14:55 UTC
Every time I update the version of the enhancer all my enchancer configs are reseted, theme, dark+ color, tray options(I like to desactivate the close to the tray) and enhancements selected

Windows 10, desktop app

**Comment by dragonwocky** [comment] 2020-08-31 22:03
how do you update?

**Comment by Guilherme5342** [comment] 2020-08-31 22:07
using npm i -g notion-enhancer on the cmd

**Comment by dragonwocky** [comment] 2020-08-31 22:08
do you remove the previous version?

**Comment by Guilherme5342** [comment] 2020-08-31 22:09
no

**Comment by Guilherme5342** [comment] 2020-08-31 22:09
I and I don't unapply it

**Comment by dragonwocky** [comment] 2020-08-31 22:09
alright found the bug, will be fixed in the next release (though since it's still in the current version it will still happen that once).

**Closed** 2020-09-20 05:51 UTC
Labels: bug

**Comment by theotheo** [comment] 2022-02-13 21:58
I've met the same issue. I am on Ubuntu and not sure that it related to app's update. It seems the settings just reset periodically.
It's a bit annoying. Any advice would be appreciated!

**Comment by dragonwocky** [comment] 2022-02-13 23:03
@theotheo though the "symptoms" appear similar, the cause and situation in which the settings reset occur are different. Please open a new bug report in https://github.com/notion-enhancer/repo for this - my guess is that it's related to having too many tabs open at once.
