### ISSUE TITLE
Notion doesn't launch

### ISSUE THREAD

**Issue by VkinOe** [dragonwocky/notion-enhancer#247] opened 2020-11-11 22:16 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
When I try to open Notion, it doesn't stop loading and never finishes

**expected behaviour**
why is this a bug - what should be happening?
Notion should be opening normally

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/46370042/98870698-f8dcf000-2473-11eb-8833-0f5e4946992f.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10

**Comment by dragonwocky** [comment] 2020-11-12 00:42
duplicate of #197, fix will be released soon. please read existing issues before opening a new one.

**Closed by dragonwocky** 2020-11-12 00:42 UTC
Labels: bug, duplicate
