### ISSUE TITLE
The enhancement effect is only "half done".

### ISSUE THREAD

**Issue by LeonWong0609** [dragonwocky/notion-enhancer#44] opened 2020-08-16 13:04 UTC
**describe the bug**
The enhancement effect is only "half done". (See the screenshot)

**expected behaviour**
The Windows 10 stock title bar should disappear (as the screenshot in README). 

**screenshots**
![screenshot](https://user-images.githubusercontent.com/58762081/90334922-9787bb00-e003-11ea-8b36-8ffa902f1e8d.png)

**platform**
Windows 10

Thanks ❤️

**Comment by dragonwocky** [comment] 2020-08-16 13:06
duplicate of #43 and #38 - known bug due to a recent notion update, already fixed in the wip beta, i'm doing what i can do get it done, just be patient a few more days.

**Closed by dragonwocky** 2020-08-16 13:06 UTC
Labels: bug

**Comment by LeonWong0609** [comment] 2020-08-16 13:08
Sorry I forgot to read the previous issues, thank you for your reply!
