### ISSUE TITLE
Propert layout enhancement non-functional

### ISSUE THREAD

**Issue by pranjalshah9814ps** [dragonwocky/notion-enhancer#86] opened 2020-09-05 10:46 UTC
This bug pertains to the "property layout" enhancement.

**Describe the bug**
Whenever I open a page, the properties section appears as normal (i.e. as it would without the enhancement), not collapsed and without an option to collapse it manually

**Expected behaviour**
The properties section of the page should have been collapsed with all the properties hidden or at the very least with an option to collapse this section.

**Screenshots**
Expected: ![image](https://user-images.githubusercontent.com/62697064/92303387-f5b81600-ef91-11ea-968e-1b04c17f79eb.png)

Bug: ![image](https://user-images.githubusercontent.com/62697064/92303364-a1ad3180-ef91-11ea-85ea-ef099e0d1b1a.png)

**Platform**
Windows 10 v2004

**Comment by dragonwocky** [comment] 2020-09-05 10:47
duplicate of https://github.com/dragonwocky/notion-enhancer/issues/57, every time i fix it notion updates things again :/

**Comment by pranjalshah9814ps** [comment] 2020-09-05 11:04
No worries!
Sorry about the duplicate issue.
Great work with the enhancer BTW! Love it!

**Closed** 2020-09-20 05:51 UTC
Labels: bug
