### ISSUE TITLE
Remappable Keyboard-Shortcuts

### ISSUE THREAD

**Issue by N1cl4s** [dragonwocky/notion-enhancer#188] opened 2020-11-02 10:18 UTC
**problem**
why do you need this feature? e.g. smoother app experience, sharing/displaying content for other users, ____ always frustrates you

Custom Key-bindings for keyboard-shortcuts

**solution**
how do you want this feature to appear/act? do you have any suggestions for how it could be implemented?
An option in the settings-menu would be great, where we could remap common/all available keyboard-shortcuts

**alternatives (optional)**
have you tried to do this yourself? have you seen it done somewhere else?
would a different feature remove the need for this?
I have not tried this by myself as I have no clue how :)

**Comment by dragonwocky** [comment] 2020-11-02 10:31
duplicate of #137 and not possible at the moment (see #137 for an explanation).

**Closed by dragonwocky** 2020-11-02 10:31 UTC
Labels: duplicate, enhancement
