### ISSUE TITLE
Open up notion when clicking desktop shorcut

### ISSUE THREAD

**Issue by humleflue** [dragonwocky/notion-enhancer#113] opened 2020-09-22 10:22 UTC
**problem**
I keep pressing the Notion-shortcut on my desktop instead of the small tray icon. When I do nothing happens, which is frustrating.

**solution**
Open up Notion, when clicking a shortcut

**Comment by dragonwocky** [comment] 2020-09-22 12:40
which shortcut are you pressing?

**Comment by dragonwocky** [comment] 2020-09-25 02:35
this doesn't make any sense to me, so I'm closing this issue until further information is reported

**Comment by dragonwocky** [comment] 2020-09-25 02:56
reopening after a better explanation from discord:

"when you close notion and the enhancer option to remain in the tray is active you can't open notion using the normal shortcut, you need to use the tray icon
the shortcut being the taskbar icon or the desktop one"

**Comment by bearded22** [comment] 2020-10-06 07:20
I'm experiencing the same issue as @humleflue. This only happens when "closing" notion instead of "minimising it".
two following things do work:

1. Right click on the notion icon in your Dock click Quit and then just re-open.
2. Go to the notion enhancer icon in the status bar and click "new window".

So basically the issue is that just clicking the icon on your Dock will no-longer open up notion once notion has been closed.

**Comment by dragonwocky** [comment] 2020-10-06 08:41
@bearded22 if you have the "close window to tray" option on, then all that happens when you close notion is that it's hidden. 
it's not actually closed unless you "quit" from the __tray__ (not dock).

since the app is still open the dock won't create a new window, but it also can't show the already-open window since it's hidden in a non-focusable state. you can show the window either by clicking the tray icon or using the keyboard shortcut (by default `Cmd/Ctrl+Shift+A`).

ideally when you click the dock icon it mimics the behaviour of clicking the tray icon and shows the hidden windows, but I'm yet to find a way to do that.

if you'd rather not have this always-open-in-the-background behaviour, just toggle the "close window to tray" option off.

**Comment by humleflue** [comment] 2020-10-11 19:13
Sorry for the bad explanation, but yes - I meant what the guy on Discord wrote. Even though I understand your explanation, It's still some very confusing behavior.

**Comment by dragonwocky** [comment] 2020-10-11 19:26
And that's why it's a bug and should be kept open until fixed

**Closed** 2020-11-02 05:17 UTC
Labels: awaiting release, bug
