### ISSUE TITLE
Windows desktop app would not load day after enhancer instalation

### ISSUE THREAD

**Issue by mgavish** [dragonwocky/notion-enhancer#245] opened 2020-11-11 14:45 UTC
I installed notion-enhancer yesterday and it seemed to work fine though my windows 10 desktop app would not load today.  I removed notion-enhancer through the command line and that fixed the problem.

**Comment by DavidBradbury** [comment] 2020-11-11 16:22
I ran into the same issue. Restarted my machine and Notion was stuck loading. Windows 10. 

Expanding on what mgavish said, I ran:
```
npm remove -g notion-enhancer
npm i -g notion-enhancer
```

And everything worked again.

**Comment by dragonwocky** [comment] 2020-11-11 20:43
duplicate of #197, fix will be released soon. please read existing issues before opening a new one.

**Closed** 2020-11-12 00:41 UTC
Labels: bug, duplicate
