### ISSUE TITLE
Weekly View date blocks don't expand to fit content.

### ISSUE THREAD

**Issue by nate-york** [dragonwocky/notion-enhancer#96] opened 2020-09-10 03:09 UTC
**describe the bug**
"weekly" view date blocks don't grow to accommodate more than one card and cut off content.

**expected behaviour**
regular calendar views get taller to see all cards on a day

**screenshots**
![imgur](https://i.imgur.com/d8cU1z0.png)

**platform**
win10

**Comment by dragonwocky** [comment] 2020-09-10 03:16
duplicate of https://github.com/dragonwocky/notion-enhancer/issues/76, fix will be released soon

**Comment by nate-york** [comment] 2020-09-10 03:18
Ah cool, thanks. I searched before I posted but wasn't including closed issues. Looking forward to the fix, thanks!

**Closed** 2020-09-20 05:51 UTC
Labels: bug
