### ISSUE TITLE
Notion installed via scoop

### ISSUE THREAD

**Issue by UniqueYang** [dragonwocky/notion-enhancer#82] opened 2020-09-04 17:00 UTC
**platform**
windows

**installation steps**
how did you install notion?
[Scoop](https://github.com/lukesampson/scoop)

**filepaths**
my scoop custom directory:
`D:\\Scoop\\apps\\notion\\current\\resources`
The structure is the same as the official one.

**how?**
Can you consider where the scoop will be installed? I just change `folder` in notion-enhancer/pkg/helpers.js is not working, I don't know what's going on. 
Can you improve it? Or you can tell me how to modify it to fit the situation.

**Comment by dragonwocky** [comment] 2020-09-04 22:58
duplicate of https://github.com/dragonwocky/notion-enhancer/issues/78 - use the official windows build.
at the moment, scoop is not supported (and there's no real difference/benefit that i can find of installing notion via scoop instead of the normal installation).

**Closed** 2020-09-04 22:58 UTC
Labels: enhancement

**Comment by 2bon** [comment] 2021-08-12 02:48
> duplicate of #78 - use the official windows build.
> at the moment, scoop is not supported (and there's no real difference/benefit that i can find of installing notion via scoop instead of the normal installation).

scoop is faster then stupid downLoad .
why I can see 
`scoop update notion
notion:  (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'`
