### ISSUE TITLE
After enhancer installation Notion-app isn't working

### ISSUE THREAD

**Issue by zerj23** [dragonwocky/notion-enhancer#173] opened 2020-10-22 08:59 UTC
The app doesn't start, can't find nothing related to notion exept for this in journald log.
22/10/20 10:49	systemd	app-notion\x2dapp-7aaeef7a0e584d52a5905146723bc23a.scope: Succeeded.
22/10/20 10:48	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 65246, resource id: 33555389, major code: 18 (ChangeProperty), minor code: 0
Already tried to remove and re-apply the mod with no success.
If i remove the mod works without issues
**platform**
Arch Linux, notion-app 1:2.0.8-4, notion-enhancer 0.9.1-1, both installed via AUR.

**Comment by dragonwocky** [comment] 2020-10-22 09:06
the notion-app package launch script has changed a bit, enhancer support is still catching up. it'll be fixed in the next release. for now, go into `/usr/bin/notion-app` and/or `/opt/notion-app/notion-app` and replace `app.asar` with `app`.

**Comment by Astatine-213-Tian** [comment] 2020-10-24 07:51
I met the same problem on Mac!

**Comment by dragonwocky** [comment] 2020-10-24 08:38
@Astatine-213-Tian no, you didn't. This problem was caused by changes specifically to the version of the app for Linux. You've had a similar outcome for a different reason.
Can you provide a screenshot of what it says when you try install the enhancer?

**Closed** 2020-11-02 05:17 UTC
Labels: awaiting release, bug
