### ISSUE TITLE
cant hide both title bar and menu bar at the same time

### ISSUE THREAD

**Issue by Blacksuan19** [dragonwocky/notion-enhancer#69] opened 2020-08-31 11:25 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
cant hide both menu bar and title bar

**expected behaviour**
Both menu bar and title bar can be hidden without having to choose either. For example, the screenshot below is from the old version where all i needed to achieve this was my theme css and to remove the titlebar section from preload.js
![2020-08-26_09-12](https://user-images.githubusercontent.com/10248473/91714847-262d3800-ebbf-11ea-9544-843af8d4bba1.png)

**screenshots**
current behavior in the enhanced menu I have tried disabling integrated title bar and set frameless drag area > 0 but still cant hide it 
![2020-08-31_19-24](https://user-images.githubusercontent.com/10248473/91715093-9f2c8f80-ebbf-11ea-9be8-5328798229f6.png)

**platform**
arch linux

**Comment by dragonwocky** [comment] 2020-08-31 11:40
if you managed to do that before, that was a bug. it's not supposed to be possible, as then you can't control the window properly (not even move it). current behaviour is as intended - it's either frameless with integrated buttons or native.

what's your purpose here? closing because this isn't a bug, but i'm curious.

**Comment by Blacksuan19** [comment] 2020-08-31 11:58
that is the point, i use a tiling window manager you're not able to move, maximize or minimize the windows so both the drag area and the title bar are very useless to me so i always hide them

**Comment by dragonwocky** [comment] 2020-08-31 12:18
alright yeah that's a pretty niche case. if i have time tomorrow i might be able to build you a solution but it's not smth i'll put into the main release.

**Comment by Blacksuan19** [comment] 2020-08-31 12:37
that would be great, I know other users of notion who also happen to be using a tiling wm so we would appreciate if this was an implemented feature rather than a special version

**Comment by dragonwocky** [comment] 2020-09-17 04:53
this will be doable by toggling the "tiling window manager mode" option under the core extension.

**Comment by Blacksuan19** [comment] 2020-09-17 06:48
that's great!
just tried latest alpha, and it works as expected.

**Closed** 2020-09-20 05:51 UTC
Labels: bug
