### ISSUE TITLE
Windows default titlebar not removed

### ISSUE THREAD

**Issue by S3rene** [dragonwocky/notion-enhancer#50] opened 2020-08-27 12:28 UTC
**describe the bug**
The default Windows titlebar still remains at top of window while new titlebar is added

**expected behaviour**
Default Windows titlebar should be replaced entirely

**screenshots**
![image](https://user-images.githubusercontent.com/40626327/91428572-0fba7000-e891-11ea-886a-bd84333be8c9.png)

**platform**
Win10 with Python 3.8.5

_Note: The person submitting this is not good with technology. If this is not a bug, I'm sorry._

**Comment by dragonwocky** [comment] 2020-08-27 12:31
this is a bug, but is a duplicate of #43 and will be fixed in the update i'm releasing in ~an hour.

**Closed by dragonwocky** 2020-08-27 12:31 UTC
Labels: bug
