### ISSUE TITLE
Weekend overlay covered card on weekend days

### ISSUE THREAD

**Issue by vivavu** [dragonwocky/notion-enhancer#249] opened 2020-11-12 02:35 UTC
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
The new timeline feature has a overlay bug. Weekend overlay covers a card if it is dated on weekend

**expected behaviour**
Card should be on top of the overlay on timeline weekends.

**screenshots**
![image](https://user-images.githubusercontent.com/10050836/98888324-13c15b80-2498-11eb-9370-40126b5d1b3f.png)

**platform**
Windows 10 Pro 20H2 build19402.630

**Comment by dragonwocky** [comment] 2020-11-12 02:46
duplicate of #248

**Closed by dragonwocky** 2020-11-12 02:46 UTC
Labels: bug
