### ISSUE TITLE
重启失效 报错

### ISSUE THREAD

**Issue by chezhongkun** [dragonwocky/notion-enhancer#213] opened 2020-11-05 14:50 UTC
Process:               Notion [13060]
Path:                  /Applications/Notion.app/Contents/MacOS/Notion
Identifier:            Notion
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Notion [13060]
User ID:               501

Date/Time:             2020-11-05 22:48:41.915 +0800
OS Version:            macOS 11.0.1 (20B5012d)
Report Version:        12
Bridge OS Version:     5.0.1 (18P52551s)
Anonymous UUID:        596AD42E-C21D-14FE-FFB9-887A8B4AD177

Sleep/Wake UUID:       23E23B8A-1D3B-4E71-B4FE-3FB0D7607EBD

Time Awake Since Boot: 37000 seconds
Time Since Wake:       21000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                      10478c000-1047b6000    [  168K] r-x/rwx SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000106863000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeeb473c18
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000106863000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Thread 0 instruction stream not available.

Thread 0 last branch register state not available.

Binary Images:
       0x10478c000 -        0x1047b5fff +??? (0) <09E43234-E7F5-3BD2-A492-B374F6A2E494> (null)
       0x106862000 -        0x1068fdfff +??? (832.7) <0268A2CB-33B1-392A-B968-B875708CCD9A> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 57649
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1044K resident=0K(0%) swapped_out_or_unallocated=1044K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             240K        4 
__DATA_CONST                        32K        1 
__LINKEDIT                         268K        3 
__TEXT                             792K        2 
===========                     =======  ======= 
TOTAL                             65.3M       12 

Model: MacBookPro16,1, BootROM 1554.40.41.0.0 (iBridge: 18.16.12551.5.19,0), 8 processors, 8-Core Intel Core i9, 2.4 GHz, 32 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5500MItem, AMD Radeon Pro 5500M, spdisplays_pcie_device, 8 GB
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, -
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Sep 11 2020 17:01:15 version 9.30.440.2.32.5.61 FWID 01-1d69e4b4
Bluetooth: Version 8.0.1f5, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB3.0 Hub
USB Device: USB 3.1 Bus
USB Device: USB2.0 Hub
USB Device: USB 2.0 Hub
USB Device: USB3.0 Card Reader
USB Device: USB C Video Adaptor
USB Device: USB Billboard Device
USB Device: USB2.0 Hub
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 58.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 58.1

**Comment by dragonwocky** [comment] 2020-11-06 03:03
title doesn't mean anything to me, but content looks like a duplicate of #212

**Closed by dragonwocky** 2020-11-06 03:03 UTC
Labels: bug, duplicate
