### ISSUE TITLE
Conflicting keybinds

### ISSUE THREAD

**Issue by chhoumann** [dragonwocky/notion-enhancer#77] opened 2020-09-03 08:24 UTC
**Problem**
Notion inline code (CTRL+E) key shortcut conflicts with the Notion Enhancer 'Show Enhancements' keybind.

**Solution**
A simple solution would be to let users specify their own keybindings. Alternatively, to remap the key to Alt+E, which has no conflicts with Notion that I know of. CommandOrControl+Shift+E would not work, since that is the key shortcut for inline mathematical equations in Notion.

**Alternatives (optional)**
I could not make a Pull request due to not having the permissions, so I have included the code to change this on windows machines.

tray.js from line 155
```javascript
{
    type: 'normal',
    label: 'Enhancements',
    accelerator: 'Alt+E',
    click: openExtensionMenu,
},
```

client.js from line 20
```javascript
  document.defaultView.addEventListener('keyup', (event) => {
    if (event.code === 'F5') location.reload();
    if (event.key === 'e' && (event.altKey || event.metaKey))
      electron.ipcRenderer.send('enhancer:open-extension-menu');
  });
```

**Comment by dragonwocky** [comment] 2020-09-03 08:28
duplicate of https://github.com/dragonwocky/notion-enhancer/issues/70
it will be changed to `alt+e` and made configurable in v0.9 (already coded/fixed, not yet released)

**Closed by dragonwocky** 2020-09-03 08:28 UTC
Labels: enhancement
