### ISSUE TITLE
Ctrl + E shortcut customisation

### ISSUE THREAD

**Issue by swissarmysam** [dragonwocky/notion-enhancer#87] opened 2020-09-05 12:04 UTC
**problem**
Ctrl + E shortcut for inline code opens notion enhancer GUI

**solution**
Allow shortcut to be changed in notion enhancer GUI

**Comment by dragonwocky** [comment] 2020-09-05 12:07
duplicate of https://github.com/dragonwocky/notion-enhancer/issues/70, will be fixed in the next release

**Closed by dragonwocky** 2020-09-05 12:07 UTC
Labels: enhancement
